version: '3' 
services: 
    react: 
        build: ./ 
        volumes: 
            - ./:/nodeapp 
            - /nodeapp/node_modules 
        ports: 
            - "3000:8080"
        stdin_open: true
        tty: true 


